name: Build melashri/polynote & Push to Dockerhub

on:
  workflow_dispatch:
  #schedule:
   # - cron: '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: melashri/polynote
        tags: latest
